include:
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_common.yml
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_pop.yml
  - project: releng/common-gitlab-ci
    ref: master
    file: report-generator.yml

default:
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.225
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .m2

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2 -Xss4M"
  ENABLE_E2E_BUILD:
    value: "false"
    description: "Enable E2E build. Set to 'true' to publish hpi to Artifactory."
  E2E_BUILD_CHANGELIST:
    value: "rc1"
    description: "Changelist suffix for the release version (e.g. rc1 produces version 2.1.0-rc1). Must not end with SNAPSHOT. After fixing E2E bugs, use the changeList as rc2, rc3, rc4 etc. to provide new E2E build."
  GENERATE_REPORTS:
    value: "false"
    description: "Generate and publish reports (SBOM, VDR) and publish to Artifactory. Set to 'true' to enable report generation and publishing."

stages:
  - test
  - build
  - analysis
  - e2e_build
  - sbom_vdr
  - notification

unit_test_and_coverage_report:
  stage: test
  only:
    - merge_requests
    - main
    - branches
  script:
    - |
      echo "Running Tests and generating code coverage report..."
      ./mvnw clean verify
      echo "Extracting code coverage percentage..."
      JACOCO_XML="target/site/jacoco/jacoco.xml"
      if [ -f "$JACOCO_XML" ]; then
        MISSED=$(grep -oP '<counter type="LINE"[^/]*missed="\K[0-9]+' "$JACOCO_XML" | tail -1)
        COVERED=$(grep -oP '<counter type="LINE"[^/]*covered="\K[0-9]+' "$JACOCO_XML" | tail -1)
        TOTAL=$((MISSED + COVERED))
        if [ "$TOTAL" -gt 0 ]; then
          COVERAGE=$(awk "BEGIN {printf \"%.2f\", ($COVERED/$TOTAL)*100}")
          echo "Total Code Coverage: ${COVERAGE}%"
        else
          echo "No coverage data found."
        fi
      else
        echo "jacoco.xml not found!"
      fi
  artifacts:
    expire_in: 3 days
    paths:
      - target/site/jacoco
    reports:
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
  coverage: /Total Code Coverage:\s+([\d\.]+)%/

build:
  stage: build
  script:
    - |
      echo "Building project..."
      ./mvnw clean install -DskipTests
  artifacts:
    paths:
      - "**/target/*.hpi"
      - "**/target/*.jar"

new_pop_blackduck:
  stage: analysis
  rules:
    - if: $CI_COMMIT_BRANCH
  allow_failure: true
  extends: .new_pop_blackduck_analysis
  variables:
    DETECT_PROJECT_NAME: "blackduck-security-scan-plugin"
    DETECT_MAVEN_EXCLUDED_SCOPES: "test"
    DETECT_ACCURACY_REQUIRED: "NONE"
  before_script:
    - |
      apt -y update
      apt -y install make python3 python3-pip
      pip install blackduck requests
      export RELEASE_VERSION=`git describe --tags --abbrev=0 2>/dev/null || echo ''`
      mkdir -p $HOME/.docker
      touch $HOME/.docker/config.json
      echo "$DOCKER_AUTH_CONFIG" >> $HOME/.docker/config.json
      # Set Project Version for Black Duck Hub
      export DETECT_PROJECT_VERSION_NAME=$(./mvnw help:evaluate -Dexpression=revision -q -DforceStdout)
      

polaris_bridge:
  stage: analysis
  rules:
    - if: $CI_COMMIT_BRANCH
  allow_failure: true
  variables:
    DETECT_MAVEN_EXCLUDED_SCOPES: "test"
    BRIDGE_POLARIS_PROJECT_NAME: "blackduck-security-scan-jenkins-plugin"
    BRIDGE_COVERITY_CLEAN_COMMAND: "./mvnw clean"
    BRIDGE_COVERITY_BUILD_COMMAND: "./mvnw install -DskipTests"

release_qa:
  stage: e2e_build
  rules:
    - if: $ENABLE_E2E_BUILD == "true"
  script:
    - |
      echo "Publishing artifacts to internal Artifactory..."
      mkdir -p ${CI_PROJECT_DIR}/.m2
      cat > ${CI_PROJECT_DIR}/.m2/settings.xml <<EOF
      <settings>
        <servers>
          <server>
            <id>bds-artifactory</id>
            <username>${ARTIFACTORY_USER}</username>
            <password>${ARTIFACTORY_PASSWORD}</password>
          </server>
        </servers>
      </settings>
      EOF
      ./mvnw -U clean install deploy -Pqa-deployment \
        -s ${CI_PROJECT_DIR}/.m2/settings.xml \
        -Dchangelist=${E2E_BUILD_CHANGELIST} \
        -DskipTests \
        -DqaArtifactoryUrl=${QA_ARTIFACTORY_URL} \
        -DsnapshotArtifactoryUrl=${SNAPSHOT_ARTIFACTORY_URL} \
        -Dspotbugs.skip=true \
        -Dspotless.check.skip=true
  after_script:
    - rm -f ${CI_PROJECT_DIR}/.m2/settings.xml
  artifacts:
    paths:
      - "**/target/*.hpi"
      - "**/target/*.jar"

.export_reports_variables:
  before_script:
    - export PACKAGE_VERSION=$(./mvnw help:evaluate -Dexpression=revision -q -DforceStdout)
    - export ARTIFACTORY_UPLOAD_REPO=1
    - export SBOM_ART_TOKEN_VAULT_PATH=sbom/integrations/blackduck-security-scan-plugin
    - export PRODUCT=Integrations
    - export GENERATE_CONFIGURATION_FILE=1
    - export GENERATION_OPTIONS="--entry blackduck-security-scan-plugin:$PACKAGE_VERSION"
    - export PRODUCT_ADDON_SBOM_OPTIONS="--output-zipfile blackduck-security-scan-plugin-$PACKAGE_VERSION-{report_type}.zip --artifactory-repo integrations-sbom/blackduck-security-scan-jenkins"

generate_and_publish_sbom_vdr_reports:
  stage: sbom_vdr
  image: releng/base-gitlab-runner:jdk17-python3.11-git-docker
  rules:
    - if: $GENERATE_REPORTS == "true"
  extends:
    - .export_reports_variables
    - .run_sbom_generation


