include:
  - project: altair/altair-build-common
    ref: 1.0.228
    file: gitlab/ci/altair_common.yml
  - project: altair/altair-build-common
    ref: master
    file: gitlab/ci/altair_pop.yml
  - project: releng/common-gitlab-ci
    ref: master
    file: report-generator.yml

variables:
  RELEASE_QA_BUILD:
    value: "false"
    description: "Release QA (E2E) build. Set to 'true' to publish hpi to Artifactory."
  GENERATE_REPORTS:
    value: "false"
    description: "Generate and publish reports (SBOM, VDR) and publish to Artifactory. Set to 'true' to enable report generation and publishing."

stages:
  - test
  - coverage_report
  - build
  - analysis
  - release_qa
  - sbom_vdr
  - notification

unit_tests:
  stage: test
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.218
  only:
    - merge_requests
    - main
    - branches
  script:
    - |
      echo "Run unit tests..."
      mvn clean test

code_coverage:
  stage: coverage_report
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.218
  only:
    - main
    - merge_requests
    - branches
  script:
    - |
      echo "Generate code coverage report..."
      mvn clean verify
  artifacts:
    expire_in: 3 days
    paths:
      - coverage-report/target/site/jacoco-aggregate
    reports:
      coverage_report:
        coverage_format: jacoco
        path: coverage-report/target/site/jacoco-aggregate/jacoco.xml

build:
  stage: build
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.218
  script:
    - |
      echo "Building project..."
      mvn clean install -DskipTests
  artifacts:
    paths:
      - "**/target/*.hpi"
      - "**/target/*.jar"

new_pop_blackduck:
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.218
  stage: analysis
  extends: .new_pop_blackduck_analysis
  variables:
    MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2 -Xss4M
    BD_PROPERTIES: "--detect.maven.excluded.scopes=test"
    DETECT_MAVEN_EXCLUDED_MODULES: "coverage-report"
    DETECT_PROJECT_NAME: "blackduck-security-scan-plugin"
  dependencies:
    - unit_tests
    - code_coverage

polaris_bridge:
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.218
  stage: analysis
  variables:
    MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2 -Xss4M
    DETECT_MAVEN_EXCLUDED_SCOPES: "test"
    DETECT_MAVEN_EXCLUDED_MODULES: "coverage-report"
  dependencies:
    - unit_tests
    - code_coverage

release_qa:
  stage: release_qa
  image: us-docker.pkg.dev/cloudops-artifacts-prd/polarisng/altair-maven-build-jdk17:1.0.218
  rules:
    - if: $RELEASE_QA_BUILD == "true"
  variables:
    MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2 -Xss4M
  script:
    - |
      echo "Publishing artifacts to internal Artifactory..."
      mkdir -p ${CI_PROJECT_DIR}/.m2
      cat > ${CI_PROJECT_DIR}/.m2/settings.xml <<EOF
      <settings>
        <servers>
          <server>
            <id>bds-artifactory</id>
            <username>${ARTIFACTORY_USER}</username>
            <password>${ARTIFACTORY_PASSWORD}</password>
          </server>
        </servers>
      </settings>
      EOF
      mvn -U clean install deploy test -Pqa-deployment \
        -DqaArtifactoryUrl=${QA_ARTIFACTORY_URL} \
        -DsnapshotArtifactoryUrl=${SNAPSHOT_ARTIFACTORY_URL} \
        -Dspotbugs.skip=true \
        -Dspotless.check.skip=true
  artifacts:
    paths:
      - "**/target/*.hpi"
      - "**/target/*.jar"
  dependencies:
    - unit_tests
    - code_coverage

.export_reports_variables:
  before_script:
    - export PACKAGE_VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)
    - export ARTIFACTORY_UPLOAD_REPO=1
    - export SBOM_ART_TOKEN_VAULT_PATH=sbom/integrations/blackduck-security-scan-plugin
    - export PRODUCT=Integrations
    - export GENERATE_CONFIGURATION_FILE=1
    - export GENERATION_OPTIONS="--entry blackduck-security-scan-plugin:$PACKAGE_VERSION"
    - export PRODUCT_ADDON_SBOM_OPTIONS="--output-zipfile blackduck-security-scan-plugin-$PACKAGE_VERSION-{report_type}.zip --artifactory-repo integrations-sbom/blackduck-security-scan-jenkins"

generate_and_publish_sbom_vdr_reports:
  stage: sbom_vdr
  image: releng/base-gitlab-runner:jdk17-python3.11-git-docker
  rules:
    - if: $GENERATE_REPORTS == "true"
  extends:
    - .export_reports_variables
    - .run_sbom_generation


